create table nrmmo_schema.emails
(
    email_id      bigint generated always as identity,
    email_version integer default 0     not null,
    email_address varchar(254)          not null,
    email_active  boolean default false not null,
    constraint pk_emails_eui
        primary key (email_id),
    constraint chk_emails_ev
        check (email_version >= 0)
);

create table nrmmo_schema.users
(
    user_id       bigint generated always as identity,
    user_version  integer default 0     not null,
    user_name     varchar(255)          not null,
    user_password varchar(255)          not null,
    user_balance  bigint  default 0     not null,
    email_id      bigint                not null,
    user_active   boolean default false not null,
    constraint pk_users_uid
        primary key (user_id),
    constraint fk_users_eid
        foreign key (email_id)
            references nrmmo_schema.emails (email_id)
            on update cascade
            on delete no action,
    constraint chk_users_uv
        check (user_version >= 0),
    constraint chk_users_ub
        check (user_balance >= 0)
);

CREATE TABLE nrmmo_schema.user_sessions
(
    session_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    jwt_token_id     VARCHAR(255)                            NOT NULL,
    ip_address       VARCHAR(45),
    user_agent       VARCHAR(500),
    device_type      VARCHAR(100),
    browser          VARCHAR(100),
    operating_system VARCHAR(100),
    country          VARCHAR(100),
    city             VARCHAR(100),
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_activity    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_active        BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_user_sessions PRIMARY KEY (session_id)
);

ALTER TABLE nrmmo_schema.user_sessions
    ADD CONSTRAINT FK_USER_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES nrmmo_schema.users (user_id);