server:
  port: 8080

spring:
  application:
    name: netrunner-mmo-back

  ##### SPRING #####
  threads:
    virtual:
      enabled: true

  ##### DATA #####
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/nrmmo
    username: nrmmo
    password: 2wsx@WSX
  flyway:
    default-schema: migration_schema
    encoding: UTF-8
    locations: classpath:db/migration

###### SPRING DOC #####
springdoc:
  swagger-ui:
    path: /swagger-ui.html

##### ACTUATOR #####
management:
  info:
    git:
      enabled: true
      mode: full
    build.enabled: true
    java.enabled: true
    env.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  metrics:
    tags.application: netrunner-mmo-back
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

##### LOGGING #####
logging:
  level:
    net.nrmmo: debug
